#spring:
#  data:
#    mongodb:
#      host: 127.0.0.1
#      port: 27017
#      database: LawnMate
#      username: Harnan
#      username: Delini
#      password: abcd1234


#spring:
#  config:
#    import: optional:file:C:\Users\murug\Desktop\e19-3yp-Automated-grass-cutter\backend\src\main\resources\application-secret.yml
#  data:
#    mongodb:
#      host: localhost
#      port: 27017
#      database: LawnMate
#      username: mongo
#      password: abc123
#      authentication-database: LawnMate
#      authentication-mechanism: SCRAM-SHA-256 # Use only one mechanism


aws:
  access-key: ${AWS_ACCESS_KEY}
  access-secret: ${AWS_ACCESS_SECRET}
  cognito:
    userPoolId: ap-south-1_SQstNYOKe
    clientId: 5uknbnlq88jn5hh1sjm4nr77j1


spring:
  config:
    import: optional:file:C:\Users\murug\Desktop\e19-3yp-Automated-grass-cutter\backend\src\main\resources\application-secret.yml
  data:
    mongodb:
      uri: mongodb+srv://LawnMate:abcd1234@lawnmate.y5aslom.mongodb.net/
      database: LawnMate
      authentication-database: admin # Change to your authentication database
      authentication-mechanism: SCRAM-SHA-256 # Use only one mechanism
