#spring:
#  data:
#    mongodb:
#      host: 127.0.0.1
#      port: 27017
#      database: LawnMate
#      username: Harnan
#      password: abcd1234


spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: LawnMate
      username: mongo
      password: abc123
      authentication-database: LawnMate
      authentication-mechanism: SCRAM-SHA-256 # Use only one mechanism


aws:
  access-key: AKIAS6B2C4XUM3GPLPND
  access-secret: 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
  cognito:
    userPoolId: ap-south-1_SQstNYOKe
    clientId: 5uknbnlq88jn5hh1sjm4nr77j1
